apiVersion: v1
kind: ConfigMap
metadata:
  name: swich-rule
  namespace: monitoring
data:
  swich-monitoring-rules.yml: |-
    groups:
    - name: Internal-Swich-Check
      rules:
      ### ICMP
      - alert: Internal Swich ICMP Check
        annotations:
          description: "Instance {{$labels.instance}}"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "Swich ICMP not connect"
        expr: |-
          probe_success{job="Internal-ICMP-Swich"} == 0
        for: 3m
        labels:
          severity: critical

      # - alert: Swich-Monitoring-ICMP-Responce-time-1.0
      #   annotations:
      #     description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary: "ICMP response time delay"
      #   expr: |-
      #     probe_duration_seconds{job="ICMP-Swich"} >= 1.0
      #   for: 3m
      #   labels:
      #     severity: warning

      # - alert: Swich-Monitoring-ICMP-Responce-time-3.0
      #   annotations:
      #     description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary: "ICMP response time delay"
      #   expr: |-
      #     probe_duration_seconds{job="ICMP-Swich"} >= 3.0
      #   for: 3m
      #   labels:
      #     severity: warning

