apiVersion: v1
kind: ConfigMap
metadata:
  name: nas-rule
  namespace: monitoring
data:
  nas-monitoring-rules.yml: |-
    groups:
    - name: NAS-Check
      rules:
      ### ICMP
      - alert: NAS-ICMP-Check
        annotations:
          description: "Instance {{$labels.instance}}"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "NAS ICMP not connect"
        expr: |-
          probe_success{job="ICMP-NAS"} == 0
        for: 3m
        labels:
          severity: critical

      - alert: NAS-Monitoring-ICMP-Responce-time-1.0
        annotations:
          description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "ICMP response time delay"
        expr: |-
          probe_duration_seconds{job="ICMP-NAS"} >= 1.0
        for: 3m
        labels:
          severity: warning

      - alert: NAS-Monitoring-ICMP-Responce-time-3.0
        annotations:
          description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "ICMP response time delay"
        expr: |-
          probe_duration_seconds{job="ICMP-NAS"} >= 3.0
        for: 3m
        labels:
          severity: warning


      ### SSH
      - alert: NAS-SSH-Check
        annotations:
          description: "Instance {{$labels.instance}}"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "NAS SSH not connect"
        expr: |-
          probe_success{job="SSH-NAS"} == 0
        for: 3m
        labels:
          severity: critical

      - alert: NAS-Monitoring-SSH-Responce-time-1.0
        annotations:
          description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "SSH response time delay"
        expr: |-
          probe_duration_seconds{job="SSH-NAS"} >= 1.0
        for: 3m
        labels:
          severity: warning

      - alert: NAS-Monitoring-SSH-Responce-time-3.0
        annotations:
          description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "SSH response time delay"
        expr: |-
          probe_duration_seconds{job="SSH-NAS"} >= 3.0
        for: 3m
        labels:
          severity: warning
      
      
      ### HTTP
      - alert: NAS-HTTP-Check
        annotations:
          description: "Instance {{$labels.instance}}"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "NAS HTTP not connect"
        expr: |-
          probe_success{job="HTTP-NAS"} == 0
        for: 3m
        labels:
          severity: critical

      - alert: NAS-Monitoring-HTTP-Responce-time-1.0
        annotations:
          description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "HTTP response time delay"
        expr: |-
          probe_duration_seconds{job="HTTP-NAS"} >= 1.0
        for: 3m
        labels:
          severity: warning

      - alert: NAS-Monitoring-HTTP-Responce-time-3.0
        annotations:
          description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "HTTP response time delay"
        expr: |-
          probe_duration_seconds{job="HTTP-NAS"} >= 3.0
        for: 3m
        labels:
          severity: warning

      - alert: NAS-Monitoring-HTTP-StatusCode-Err
        annotations:
          description: "job {{$labels.job}} Instance {{$labels.instance}} StatusCode Err"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "StatusCode Err"
        expr: |-
          probe_http_status_code{job="HTTP-NAS"} >= 400
        for: 3m
        labels:
          severity: warning

### 細かい監視を入れる予定
      
    

      


