apiVersion: v1
kind: ConfigMap
metadata:
  name: core-server-rule
  namespace: monitoring
data:
  core-server-monitoring-rules.yml: |-
    groups:
    - name: Internal-Core-Server-Check
      rules:
      ### ICMP
      - alert: Internal Core Server ICMP Check
        annotations:
          alert_title: "Internal {{ $labels.instance }} ICMP Check"
          description: "Instance {{$labels.instance}} not connect"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "Core Server ICMP not connect"
        expr: |-
          probe_success{job="Internal-ICMP-Core-server"} == 0
        for: 3m
        labels:
          severity: critical
            
      - alert: Internal ESXi ICMP Check
        annotations:
          alert_title: "Internal {{ $labels.instance }} ICMP Check"
          description: "Instance {{$labels.instance}} not connect"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "ESXi ICMP not connect"
        expr: |-
          probe_success{job="Internal-ICMP-ESXi-Host-Core"} == 0
        for: 3m
        labels:
          severity: critical

      # - alert: Core-Server-Monitoring-ICMP-Responce-time-1.0
      #   annotations:
      #     description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary: "ICMP response time delay"
      #   expr: |-
      #     probe_duration_seconds{job="ICMP-Core-server"} >= 1.0
      #   for: 3m
      #   labels:
      #     severity: warning

      # - alert: Core-Server-Monitoring-ICMP-Responce-time-3.0
      #   annotations:
      #     description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary: "ICMP response time delay"
      #   expr: |-
      #     probe_duration_seconds{job="ICMP-Core-server"} >= 3.0
      #   for: 3m
      #   labels:
      #     severity: warning


      # ### SSH
      # - alert: Core-Server-SSH-Check
      #   annotations:
      #     description: "Instance {{$labels.instance}} not connect"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary: "Core Server SSH not connect"
      #   expr: |-
      #     probe_success{job="SSH-Core"} == 0
      #   for: 3m
      #   labels:
      #     severity: critical

      # - alert: Core-Server-Monitoring-SSH-Responce-time-1.0
      #   annotations:
      #     description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary: "SSH response time delay"
      #   expr: |-
      #     probe_duration_seconds{job="SSH-Core"} >= 1.0
      #   for: 3m
      #   labels:
      #     severity: warning

      # - alert: Core-Server-Monitoring-SSH-Responce-time-3.0
      #   annotations:
      #     description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary: "SSH response time delay"
      #   expr: |-
      #     probe_duration_seconds{job="SSH-Core"} >= 3.0
      #   for: 3m
      #   labels:
      #     severity: warning
