apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kubernetes/monitoring-namespace.yml
  - ./kubernetes/prometheus-roles.yml
  - ./kubernetes/prometheus-config2.yaml
  - ./kubernetes/prometheus-deployment.yaml
  - ./kubernetes/prometheus-nodeservice.yaml
  - ./kubernetes/exporter/node-exporter-daemonset.yml
  - ./kubernetes/exporter/components.yaml 
  - ./kubernetes/exporter/cadvisor.yaml
  - ./kubernetes/exporter/black-box.yaml
  - ./monitoring-rule/container.yml
  - ./monitoring-rule/node-rule.yaml
  - ./monitoring-rule/trafic-rule.yml
