apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kubernetes/monitoring-namespace.yml
  - ./kubernetes/prometheus-roles.yml
  - ./kubernetes/prometheus-config2.yaml
  - ./kubernetes/prometheus-deployment.yaml
  - ./kubernetes/prometheus-nodeservice.yaml
  - ./kubernetes/exporter/node-exporter-daemonset.yml
  - ./kubernetes/exporter/components.yaml
  - ./kubernetes/exporter/cadvisor.yaml
  - ./kubernetes/exporter/black-box.yaml
  - ./monitoring-rule/cdsl-Archive-rule/cdsl-*.yaml
  - ./monitoring-rule/cdsl-Core-server-rule/cdsl-*.yaml
  - ./monitoring-rule/cdsl-ESXi-rule/cdsl-*.yaml
  - ./monitoring-rule/cdsl-Firewall-rule/cdsl-*.yaml
  - ./monitoring-rule/cdsl-NAS-rule/cdsl-*.yaml
  - ./monitoring-rule/cdsl-Openvpn-rule/cdsl-*.yaml
  - ./monitoring-rule/cdsl-Router-rule/cdsl-*.yaml
  - ./monitoring-rule/cdsl-Swich-rule/cdsl-*.yaml

