apiVersion: v1
kind: ConfigMap
metadata:
  name: archive-server-rule
  namespace: monitoring
data:
  archive-server-monitoring-rules.yml: |-
    groups:
    - name: Archive-Server-Check
      rules:
      ### ICMP
      - alert: Archive-Server-ICMP-Check
        annotations:
          description: "Instance {{$labels.instance}} not connect"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "Archive Server ICMP not connect"
        expr: |-
          probe_success{job="ICMP-Archive"} == 0
        for: 3m
        labels:
          severity: critical

      - alert: Archive-Server-Monitoring-ICMP-Responce-time-1.0
        annotations:
          description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "ICMP response time delay"
        expr: |-
          probe_duration_seconds{job="ICMP-Archive"} >= 1.0
        for: 3m
        labels:
          severity: warning

      - alert: Archive-Server-Monitoring-ICMP-Responce-time-3.0
        annotations:
          description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "ICMP response time delay"
        expr: |-
          probe_duration_seconds{job="ICMP-Archive"} >= 3.0
        for: 3m
        labels:
          severity: warning

      ### SSH
      - alert: Archive-Server-SSH-Check
        annotations:
          description: "Instance {{$labels.instance}} not connect"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "Archive Server SSH not connect"
        expr: |-
          probe_success{job="SSH-Archive"} == 0
        for: 3m
        labels:
          severity: critical

      - alert: Archive-Server-Monitoring-SSH-Responce-time-1.0
        annotations:
          description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "SSH response time delay"
        expr: |-
          probe_duration_seconds{job="SSH-Archive"} >= 1.0
        for: 3m
        labels:
          severity: warning

      - alert: NAS-Monitoring-SSH-Responce-time-3.0
        annotations:
          description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "SSH response time delay"
        expr: |-
          probe_duration_seconds{job="SSH-Archive"} >= 3.0
        for: 3m
        labels:
          severity: warning

### ここから増やす予定
