apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway-deployment
  namespace: monitoring
  labels:
    app: pushgateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway-server
  template:
    metadata:
      labels:
        app: pushgateway-server
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:latest
          ports:
            - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway-service
  namespace: monitoring
spec:
  selector: 
    app: pushgateway-server
  type: NodePort
  ports:
    - port: 8120
      targetPort: 9091
      nodePort: 30040
