apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - monitoring-master-ml:32500

    rule_files:
      - "/etc/prometheus/rules/*.yml"
        #remote_read:
        #  - url: "http://outside-prometheus-ml4:30090/api/v1/read"
        #read_recent: true

    scrape_configs:
      ##### [monitoring-target-internal]
      ## [ICMP]
      - job_name: 'Internal-ICMP-Router' #Routerオンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
              - 192.168.100.1  # ASUS TUF-AX5400 (ルータ1)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'Internal-ICMP-Swich' #Swichオンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
            - 192.168.100.10 #TP LINK TL-SG116E(SW-Local1)
            - 192.168.100.11 #TP LINK TL-SG116E(SW-Local3)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'Internal-ICMP-Firewall' #Farewallオンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
            - 192.168.100.15 #Buffalo WSR-2533DHPL(Router to DMZ)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'Internal-ICMP-NAS' #NASオンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
              - 192.168.100.3 #Synology DS1621xs+(Natadecoco)
              - 192.168.100.5 #Synology DS1618+(Tapioca)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'Internal-ICMP-ESXi-Host' ###ESXiが入った物理機器オンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
            - 192.168.100.21 # plum (ESXi)
            - 192.168.100.22 # jasmine (ESXi)
            - 192.168.100.23 # rose (ESXi)
            - 192.168.100.24 # lotus (ESXi)
            - 192.168.100.25 # violet (ESXi)
            - 192.168.100.26 # mint (ESXi)
            - 192.168.100.27 # lily (ESXi) 
            - 192.168.100.32 # Canele (ESXi)
            - 192.168.100.33 # Makaron (ESXi)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'Internal-ICMP-Archive' #Archiveオンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
              - 192.168.100.31 #Archive server
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

            
      # Core-server(ICMP)
      - job_name: 'Internal-ICMP-Core-server' #Core-serverオンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
            - 192.168.100.35 # Core-s1
            - 192.168.100.36 # Core-s2
            - 192.168.100.37 # Core-s3
            - 192.168.100.38 # Core-s4
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      ## [SSH]
      - job_name: 'Internal-SSH-NAS'
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [ssh_banner]
        static_configs:
          - targets:
            - 192.168.100.3:22  # natadecoco (NAS)
            - 192.168.100.5:22  # tapioca (NAS)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'Internal-SSH-Archive'
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [ssh_banner]
        static_configs:
          - targets:
            - 192.168.100.31:22 # Archive server (アーカイブサーバー)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'Internal-SSH-Core'
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [ssh_banner]
        static_configs:
          - targets:
            - 192.168.100.35:22 # Core-s1
            - 192.168.100.36:22 # Core-s2
            - 192.168.100.37:22 # Core-s3
            - 192.168.100.38:22 # Core-s4
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000
     
      ## [HTTP]
      - job_name: "Internal-HTTP-ESXi"
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - 192.168.100.21 # plum (ESXi)
            - 192.168.100.22 # jasmine (ESXi)
            - 192.168.100.23 # rose (ESXi)
            - 192.168.100.24 # lotus (ESXi)
            - 192.168.100.25 # violet (ESXi)
            - 192.168.100.26 # mint (ESXi)
            - 192.168.100.27 # lily (ESXi) #ここはDoktorの運用が始まったらなくす(これはなくていい)
            #- 192.168.201.2  # Iris
            - 192.168.100.32 # Canele (コアサーバー1)
            - 192.168.100.33 # Makaron (コアサーバー2)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000
      
      - job_name: "Internal-HTTP-NAS"
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - 192.168.100.3  # natadecoco (NAS)
            - 192.168.100.5  # tapioca (NAS)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000


      ### ハイパーバイザ単位の監視(完成)
      - job_name: 'Internal-ESXI_exporter' # ESXiExporter用
        scrape_interval: 30s
        static_configs:
          - targets: ['monitoring-master-ml:32700'] # Jasmine
          - targets: ['monitoring-master-ml:32702'] # Lotus
          - targets: ['monitoring-master-ml:32704'] # Mint
          - targets: ['monitoring-master-ml:32705'] # Plum
          - targets: ['monitoring-master-ml:32701'] # Rose
          - targets: ['monitoring-master-ml:32703'] # Violet
          - targets: ['monitoring-master-ml:32706'] # Lily
          #- targets: ['monitoring-master-ml:32707'] # Iris
          - targets: ['monitoring-master-ml:32709'] # Canele
          - targets: ['monitoring-master-ml:32708'] # Makaron

      ### ここからNode単位(未完成)
      - job_name: 'Internal-archive-node-exporter'
        scrape_interval: 30s
        static_configs:
          - targets: ['192.168.100.31:9100']

      ### Core-serverの監視
      - job_name: 'Internal-Core-server-systemd-exporter'
        scrape_interval: 30s
        static_configs:
          - targets: ['192.168.100.35:9558']
          - targets: ['192.168.100.36:9558']
          - targets: ['192.168.100.37:9558']
          - targets: ['192.168.100.38:9558']


      ### ここからDoktorの開発環境の対象の設定
      - job_name: 'ICMP-Doktor-dev' #Core-serverオンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
            - doktor-m-v2
            - doktor-worker1-v2
            - doktor-worker2-v2
            - doktor-worker3-v2
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'SSH-Doktor-dev'
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [ssh_banner]
        static_configs:
          - targets:
            - doktor-m-v2:22
            - doktor-worker1-v2:22
            - doktor-worker2-v2:22
            - doktor-worker3-v2:22
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'doktor-dev-node'
        scrape_interval: 30s
        static_configs:
          - targets: ['doktor-m-v2:9100']
          - targets: ['doktor-worker1-v2:9100']
          - targets: ['doktor-worker2-v2:9100']
          - targets: ['doktor-worker3-v2:9100']

      ## [HTTP]
      - job_name: "Doktor-Dev-http-page"
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - doktor-m-v2
            - doktor-worker1-v2
            - doktor-worker2-v2
            - doktor-worker3-v2
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: doktor-m-v2:32200

      - job_name: 'Doktor-Dev-Cadvisor'
        scrape_interval: 30s
        static_configs:
          - targets: ['doktor-m-v2:30080']

      
      ##### [monitoring-target-external]
      ## [ICMP]
      - job_name: 'External-ICMP-Router' #Routerオンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
              - 192.168.201.1  # ASUS Router 11ax(ルータ2)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'External-ICMP-ESXi-Host' ###ESXiが入った物理機器オンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
            - 192.168.201.2  # Iris
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      ## [HTTP]
      - job_name: "External-HTTP-ESXi"
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - 192.168.201.2  # Iris
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      ## ESXi(Irisに対するESXi-exporterの監視)
      - job_name: 'External-ESXI_exporter' # ESXiExporter用
        scrape_interval: 30s
        static_configs:
          - targets: ['monitoring-master-ml:32707'] # Iris
      
      ## External-Doktor-prod-icmp(ICMP)
      - job_name: 'External-ICMP-Doktor-prod' 
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
            - 192.168.201.8
            - 192.168.201.9
            - 192.168.201.10
            - 192.168.201.11
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      ## External-Doktor-prod-ssh(SSH)
      - job_name: 'External-SSH-Doktor-prod'
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [ssh_banner]
        static_configs:
          - targets:
            - 192.168.201.8:22
            - 192.168.201.9:22
            - 192.168.201.10:22
            - 192.168.201.11:22
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      ## Doktorの本番環境のノード
      - job_name: 'External-doktor-prod-node'
        scrape_interval: 30s
        static_configs:
          - targets: ['192.168.201.8:9100']
          - targets: ['192.168.201.9:9100']
          - targets: ['192.168.201.10:9100']
          - targets: ['192.168.201.11:9100']

      # OpenVPNに対する疎通確認
      - job_name: 'External-ICMP-OpenVPN'
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
              - 192.168.200.1
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 192.168.201.8:32200

      ## [HTTP]
      - job_name: "External-Doktor-http-page"
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - http://192.168.201.8/
            - http://192.168.201.9/
            - http://192.168.201.10/
            - http://192.168.201.11/
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 192.168.201.8:32200

      ## Internal-esxi-backup(ESXiのバックアップ用のVM)
      ## [ICMP]
      - job_name: 'Internal-esxi-backup-ICMP' 
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
            - 192.168.100.250
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      ## [SSH]
      - job_name: 'Internal-esxi-backup-SSH'
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [ssh_banner]
        static_configs:
          - targets:
            - 192.168.100.250:22
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000
      
      - job_name: 'Internal-esxi-backup-node-exporter'
        scrape_interval: 30s
        static_configs:
          - targets: ['192.168.100.250:9100']

      - job_name: 'Internal-esxi-backup-systemd-exporter'
        scrape_interval: 30s
        static_configs:
          - targets: ['192.168.100.250:9558']

      #Lidar(ラズパイ)からIrisのVMへの疎通確認
      - job_name: 'Internal-TCP-lidar'
        scrape_interval: 10s
        metrics_path: /probe
        params:
          module: [tcp_connect]
        static_configs:
          - targets:
            - 192.168.201.4:8000
            - 192.168.201.6:8000
            - 192.168.201.7:8000
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 192.168.100.252:9115
        


      - job_name: 'Internal_backup_pushgateway'
        scrape_interval: 30s
        static_configs:
          - targets: ['monitoring-master-ml:30040']
