apiVersion: v1
kind: ConfigMap
metadata:
  name: doktor-dev-server-rule
  namespace: monitoring
data:
  doktor-dev-server-monitoring-rules.yml: |-
    ### Trafic
    groups:
    - name: Doktor-Dev-Node-Check
      rules:
      ### ICMP
      - alert: Doktor Dev Node ICMP Check
        annotations:
          description: "Instance {{$labels.instance}} not connect"
          runbook_url: https://cdsl-tut.esa.io/posts/2795
          summary: "Doktor Dev Server ICMP not connect"
        expr: |-
          probe_success{job="ICMP-Doktor-dev"} == 0 and ignoring(instance, job) probe_success{instance="192.168.100.21", job="Internal-ICMP-ESXi-Host"} == 1
        for: 5m
        labels:
          severity: critical

      - alert: Doktor Dev Node SSH Check
        annotations:
          description: "Instance {{$labels.instance}} not connect"
          runbook_url: https://cdsl-tut.esa.io/posts/2795
          summary: "Doktor Dev Server SSH not connect"
        expr: |-
          probe_success{job="SSH-Doktor-dev"} == 0 and ignoring(instance, job) probe_success{instance="192.168.100.21", job="Internal-ICMP-ESXi-Host"} == 1
        for: 5m
        labels:
          severity: critical

      - alert: Doktor Dev Node Memory Average Usage High 80%
        annotations:
          description: "Node: `{{$labels.instance}}`, instance: `{{$labels.instance}}` Memory Usage High"
          runbook_url: https://cdsl-tut.esa.io/posts/2795
          summary:  "Memory Usage high"
        expr: (sum(node_memory_MemTotal_bytes{job="doktor-dev-node"}) - sum(node_memory_MemAvailable_bytes{job="doktor-dev-node"})) / sum(node_memory_MemTotal_bytes{job="doktor-dev-node"}) * 100 >= 80
        for: 5m
        labels:
          severity: warning

      - alert: Doktor Dev Node Memory Average Usage High 90%
        annotations:
          description: "Node: `{{$labels.instance}}`, instance: `{{$labels.instance}}` Memory Usage High"
          runbook_url: https://cdsl-tut.esa.io/posts/2795
          summary:  "Memory Usage high"
        expr: (sum(node_memory_MemTotal_bytes{job="doktor-dev-node"}) - sum(node_memory_MemAvailable_bytes{job="doktor-dev-node"})) / sum(node_memory_MemTotal_bytes{job="doktor-dev-node"}) * 100 >= 90
        for: 5m
        labels:
          severity: critical

      - alert: Doktor Dev Node Filesystem Average Usage High 80%
        annotations:
          description: "Node: `{{$labels.instance}}`, device: `{{$labels.device}}` Filesystem Usage high"
          runbook_url: https://cdsl-tut.esa.io/posts/2795
          summary:  "Filesystem Usage high"
        expr: (1 - (sum(node_filesystem_avail_bytes{job="doktor-dev-node", mountpoint="/"}) / sum(node_filesystem_size_bytes{job="doktor-dev-node", mountpoint="/"}))) * 100 >= 80
        for: 5m
        labels:
          severity: warning

      - alert: Doktor Dev Node Filesystem Average Usage High 90%
        annotations:
          description: "Node: `{{$labels.instance}}`, device: `{{$labels.device}}` Filesystem Usage high"
          runbook_url: https://cdsl-tut.esa.io/posts/2795
          summary:  "Filesystem Usage high"
        expr: (1 - (sum(node_filesystem_avail_bytes{job="doktor-dev-node", mountpoint="/"}) / sum(node_filesystem_size_bytes{job="doktor-dev-node", mountpoint="/"}))) * 100 >= 90
        for: 5m
        labels:
          severity: critical

      - alert: Doktor Dev front page no response
        annotations:
          description: "front page no response `{{$labels.instance}}`"
          runbook_url: https://cdsl-tut.esa.io/posts/2795
          summary:  "front page no response"
        expr: probe_success{job="Doktor-Dev-http-page"} == 0 and ignoring(instance, job) probe_success{instance="192.168.100.21", job="Internal-ICMP-ESXi-Host"} == 1
        for: 5m
        labels:
          severity: critical

      - alert: Doktor Dev front page HTTP status code err
        annotations:
          description: "front page HTTP status code err `{{$labels.instance}}`"
          runbook_url: https://cdsl-tut.esa.io/posts/2795
          summary:  "status code err"
        expr: probe_http_status_code{job="Doktor-Dev-http-page"} >= 400 and ignoring(instance, job) probe_success{instance="192.168.100.21", job="Internal-ICMP-ESXi-Host"} == 1
        for: 5m
        labels:
          severity: warning

      #- alert: Doktor Dev front page HTTP responce time late 1s
      #  annotations:
      #    description: "front page HTTP responce time late 1s `{{$labels.instance}}`"
      #    runbook_url: https://cdsl-tut.esa.io/posts/2795
      #    summary:  "responce time late 1s"
      #  expr: probe_duration_seconds{job="Doktor-Dev-http-page"} >= 1
      #  for: 3m
      #  labels:
      #    severity: warning

      - alert: Doktor Dev front page HTTP responce time late 3s
        annotations:
          description: "front page HTTP responce time late 3s `{{$labels.instance}}`"
          runbook_url: https://cdsl-tut.esa.io/posts/2795
          summary:  "responce time late 3s"
        expr: probe_duration_seconds{job="Doktor-Dev-http-page"} >= 3
        for: 5m
        labels:
          severity: critical
