apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - 192.168.100.35:32500

    rule_files:
      - "/etc/prometheus/rules/*.yml"

    scrape_configs:
      - job_name: 'archive-node-exporter'
        scrape_interval: 1m
        static_configs:
          - targets: ['192.168.100.31:9100']

      - job_name: 'ESXI_Jasmine' #Jasmine
        scrape_interval: 1m
        static_configs:
          - targets: ['192.168.100.35:32700']

      - job_name: 'ESXI_Lotus'
        scrape_interval: 1m
        static_configs:
          - targets: ['192.168.100.35:32702']

      - job_name: 'ESXI_Mint'
        scrape_interval: 1m
        static_configs:
          - targets: ['192.168.100.35:32704']

      - job_name: 'ESXI_Plum'
        scrape_interval: 1m
        static_configs:
          - targets: ['192.168.100.35:32705']

      - job_name: 'ESXI_Rose'
        scrape_interval: 1m
        static_configs:
          - targets: ['192.168.100.35:32701']

      - job_name: 'ESXI_Violet'
        scrape_interval: 1m
        static_configs:
          - targets: ['192.168.100.35:32703']

      - job_name: 'ESXI_Lily'
        scrape_interval: 1m
        static_configs:
          - targets: ['192.168.100.35:32706']
 
      - job_name: 'port-ssh'
        scrape_interval: 1m
        metrics_path: /probe
        params:
          module: [ssh_banner]
        static_configs:
          - targets:
            - 192.168.100.31:22 #archive-s(Archive Server)
            - 192.168.100.32:22 #Canele(Core Server1)
            - 192.168.100.33:22 #Makaron(Core Server2)
            - 192.168.100.35:22 #Core-s1
            - 192.168.100.36:22 #Core-s2
            - 192.168.100.37:22 #Core-s3
            - 192.168.100.3:22  #natadecoco(NAS)
            - 192.168.100.5:22  #tapioca(NAS)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 192.168.100.35:30000

      - job_name: 'ICMP-Black-box'
        scrape_interval: 1m
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
              - 192.168.100.1  #ASUS TUF-AX5400(Router)
              - 192.168.100.3  #natadecoco(NAS)
              - 192.168.100.5  #tapioca(NAS)
              - 192.168.100.21 #plum(ESXi)
              - 192.168.100.22 #jasmine(ESXi)
              - 192.168.100.23 #rose(ESXi)
              - 192.168.100.24 #lotus(ESXi)
              - 192.168.100.25 #violet(ESXi)
              - 192.168.100.26 #mint(ESXi)
              - 192.168.100.27 #lily(ESXi)
              - 192.168.100.31 #archive-s(Archive Server)
              - 192.168.100.32 #Canele(Core Server1)
              - 192.168.100.33 #Makaron(Core Server2)
              - 192.168.100.35 #Core-s1
              - 192.168.100.36 #Core-s2
              - 192.168.100.37 #Core-s3
              - 192.168.201.1  #Router2
              - 192.168.201.2  #Iris
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 192.168.100.35:30000

      - job_name: "esxi-http-check"
        scrape_interval: 5m
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
              - 192.168.100.22 #jasmine(ESXi)
              - 192.168.100.23 #rose(ESXi)
              - 192.168.100.24 #lotus(ESXi)
              - 192.168.100.25 #violet(ESXi)
              - 192.168.100.26 #mint(ESXi)
              - 192.168.100.27 #lily(ESXi)
              - 192.168.100.21 #plum(ESXi)
              - 192.168.201.2  #Iris
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 192.168.100.35:30000

      - job_name: 'https_6443'
        metrics_path: /probe
        params:
          module: [https_6443]
        static_configs:
          - targets:
              - 192.168.100.35
              - 192.168.100.36
              - 192.168.100.37
              - 192.168.100.38
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 192.168.100.35:30000

              
              #      - job_name: 'OpenVPN-ICMP-Check'
              #        scrape_interval: 1m
              #        metrics_path: /probe
              #        params:
              #          module: [icmp]
              #        static_configs:
              #          - targets:
              #              - 192.168.200.1
              #        relabel_configs:
              #          - source_labels: [__address__]
              #            target_label: __param_target
              #          - source_labels: [__param_target]
              #            target_label: instance
              #          - target_label: __address__
              #            replacement: 192.168.201.8:31000

      - job_name: 'kubernetes-nodes'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

      - job_name: "service_kube-state-metrics"
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
            action: keep
            regex: kube-state-metrics
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: service

      - job_name: "daemonset_cadvisor"
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: cadvisor
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod

    remote_read:
      - url: http://192.168.100.241:30900/api/v1/read

