apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - monitoring-master-ml:32500

    rule_files:
      - "/etc/prometheus/rules/*.yml"
        #remote_read:
        #  - url: "http://outside-prometheus-ml4:30090/api/v1/read"
        #read_recent: true

    scrape_configs:
      ### 通信関連の監視
      ## [ICMP]
      - job_name: 'ICMP-Router' #Routerオンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
              - 192.168.100.1  # ASUS TUF-AX5400 (ルータ1)
              - 192.168.201.1  # ASUS Router 11ax(ルータ2)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'ICMP-Swich' #Swichオンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
            - 192.168.100.10 #TP LINK TL-SG116E(SW-Local1)
            - 192.168.100.11 #TP LINK TL-SG116E(SW-Local3)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'ICMP-Firewall' #Farewallオンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
            - 192.168.100.15 #Buffalo WSR-2533DHPL(Router to DMZ)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'ICMP-NAS' #NASオンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
              - 192.168.100.3 #Synology DS1621xs+(Natadecoco)
              - 192.168.100.5 #Synology DS1618+(Tapioca)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'ICMP-ESXi-Host' ###ESXiが入った物理機器オンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
            - 192.168.100.21 # plum (ESXi)
            - 192.168.100.22 # jasmine (ESXi)
            - 192.168.100.23 # rose (ESXi)
            - 192.168.100.24 # lotus (ESXi)
            - 192.168.100.25 # violet (ESXi)
            - 192.168.100.26 # mint (ESXi)
              #- 192.168.100.27 # lily (ESXi)
            - 192.168.201.2  # Iris
            - 192.168.100.32 # Canele (ESXi)
            - 192.168.100.33 # Makaron (ESXi)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'ICMP-Archive' #Archiveオンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
              - 192.168.100.31 #Archive server
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      # OpenVPNに対する疎通確認
      - job_name: 'ICMP-OpenVPN'
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
              - 192.168.200.1
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 192.168.201.8:30000
            
      # Core-server(ICMP)
      - job_name: 'ICMP-Core-server' #Core-serverオンリ
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
          - targets:
            - 192.168.100.35 # Core-s1
            - 192.168.100.36 # Core-s2
            - 192.168.100.37 # Core-s3
            - 192.168.100.38 # Core-s4
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      ## [SSH]
      - job_name: 'SSH-NAS'
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [ssh_banner]
        static_configs:
          - targets:
            - 192.168.100.3:22  # natadecoco (NAS)
            - 192.168.100.5:22  # tapioca (NAS)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'SSH-Archive'
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [ssh_banner]
        static_configs:
          - targets:
            - 192.168.100.31:22 # Archive server (アーカイブサーバー)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000

      - job_name: 'SSH-Core'
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [ssh_banner]
        static_configs:
          - targets:
            - 192.168.100.35:22 # Core-s1
            - 192.168.100.36:22 # Core-s2
            - 192.168.100.37:22 # Core-s3
            - 192.168.100.38:22 # Core-s4
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000
     

      ## [HTTP]
      - job_name: "HTTP-ESXi"
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - 192.168.100.21 # plum (ESXi)
            - 192.168.100.22 # jasmine (ESXi)
            - 192.168.100.23 # rose (ESXi)
            - 192.168.100.24 # lotus (ESXi)
            - 192.168.100.25 # violet (ESXi)
            - 192.168.100.26 # mint (ESXi)
              #- 192.168.100.27 # lily (ESXi)
            - 192.168.201.2  # Iris
            - 192.168.100.32 # Canele (コアサーバー1)
            - 192.168.100.33 # Makaron (コアサーバー2)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000
      
      - job_name: "HTTP-NAS"
        scrape_interval: 30s
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - 192.168.100.3  # natadecoco (NAS)
            - 192.168.100.5  # tapioca (NAS)
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: monitoring-master-ml:30000


      ### ハイパーバイザ単位の監視(完成)
      - job_name: 'ESXI_exporter' # ESXiExporter用
        scrape_interval: 30s
        static_configs:
          - targets: ['monitoring-master-ml:32700'] # Jasmine
          - targets: ['monitoring-master-ml:32702'] # Lotus
          - targets: ['monitoring-master-ml:32704'] # Mint
          - targets: ['monitoring-master-ml:32705'] # Plum
          - targets: ['monitoring-master-ml:32701'] # Rose
          - targets: ['monitoring-master-ml:32703'] # Violet
          - targets: ['monitoring-master-ml:32706'] # Lily
          - targets: ['monitoring-master-ml:32707'] # Iris
          - targets: ['monitoring-master-ml:32709'] # Canele
          - targets: ['monitoring-master-ml:32708'] # Makaron

      ### ここからNode単位(未完成)
      - job_name: 'archive-node-exporter'
        scrape_interval: 30s
        static_configs:
          - targets: ['192.168.100.31:9100']
      
      ### monitoring-Cluster専用
      - job_name: 'kubernetes-nodes'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)



      
#---いらない
 
      # # SSHポートの監視対象
      # - job_name: 'harvest-port-ssh'
      #   scrape_interval: 1m
      #   metrics_path: /probe
      #   params:
      #     module: [ssh_banner]
      #   static_configs:
      #     - targets:
      #         - 192.168.201.8:22 
      #         - 192.168.201.9:22 
      #         - 192.168.201.10:22 
      #         - 192.168.201.11:22 
      #   relabel_configs:
      #     - source_labels: [__address__]
      #       target_label: __param_target
      #     - source_labels: [__param_target]
      #       target_label: instance
      #     - target_label: __address__
      #       replacement: monitoring-master-ml:30000
    #     #Plum上に配置しているクラスタ⇨Irisに変更予定
    #   - job_name: 'harvest-node-exporter'
    #   scrape_interval: 1m
    #   static_configs:
    #     - targets: ['192.168.201.8:9100']
    #     - targets: ['192.168.201.9:9100']
    #     - targets: ['192.168.201.10:9100']
    #     - targets: ['192.168.201.11:9100']

    # # HTTPポートの監視対象
    # - job_name: "harvest-http-check"
    #   scrape_interval: 5m
    #   metrics_path: /probe
    #   params:
    #     module: [http_2xx]
    #   static_configs:
    #     - targets:
    #       - http://outside-prometheus-ml5/
    #       - http://outside-prometheus-ml5/21-2/
    #       - http://outside-prometheus-ml5/login/
    #   relabel_configs:
    #     - source_labels: [__address__]
    #       target_label: __param_target
    #     - source_labels: [__param_target]
    #       target_label: instance
    #     - target_label: __address__
    #       replacement: monitoring-master-ml:30000


    # ###ここからテスト
    # - job_name: 'ICMP-Black-box-test' #- job_name: 'ICMP-Black-box-test'
    #   scrape_interval: 1m
    #   metrics_path: /probe
    #   params:
    #     module: [icmp]
    #   static_configs:
    #     - targets:
    #       - outside-prometheus-ml5
    #       - outside-prometheus-wc1
    #       - outside-prometheus-wc2
    #       - outside-prometheus-wc3
    #   relabel_configs:
    #     - source_labels: [__address__]
    #       target_label: __param_target
    #     - source_labels: [__param_target]
    #       target_label: instance
    #     - target_label: __address__
    #       replacement: monitoring-master-ml:30000



    # - job_name: 'test'
    #   scrape_interval: 1m
    #   static_configs:
    #     - targets: 
    #       - outside-prometheus-ml5:9100
    #       - outside-prometheus-wc1:9100
    #       - outside-prometheus-wc2:9100
    #       - outside-prometheus-wc3:9100

    # # SSHポートの監視対象
    # - job_name: 'test-port-ssh'
    #   scrape_interval: 1m
    #   metrics_path: /probe
    #   params:
    #     module: [ssh_banner]
    #   static_configs:
    #     - targets:
    #       - outside-prometheus-ml5:22
    #       - outside-prometheus-wc1:22
    #       - outside-prometheus-wc2:22
    #       - outside-prometheus-wc3:22
    #   relabel_configs:
    #     - source_labels: [__address__]
    #       target_label: __param_target
    #     - source_labels: [__param_target]
    #       target_label: instance
    #     - target_label: __address__
    #       replacement: monitoring-master-ml:30000

    # - job_name: 'Black-box-http-test'
    #   scrape_interval: 1m
    #   metrics_path: /probe
    #   params:
    #     module: [icmp]
    #   static_configs:
    #     - targets:
    #       - http://outside-prometheus-ml5/
    #       - http://outside-prometheus-ml5/register/
    #       - http://outside-prometheus-ml5/login/
    #   relabel_configs:
    #     - source_labels: [__address__]
    #       target_label: __param_target
    #     - source_labels: [__param_target]
    #       target_label: instance
    #     - target_label: __address__
    #       replacement: monitoring-master-ml:30000
