apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: alert
data:
  config.yml: |-
    global:
      resolve_timeout: 1m
      slack_api_url: https://hooks.slack.com/services/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

    inhibit_rules:
      - equal:
          - namespace
          - alertname
        source_matchers:
          - severity = critical
        target_matchers:
          - severity =~ warning|info|attention
      - equal:
          - namespace
          - alertname
        source_matchers:
          - severity = warning
        target_matchers:
          - severity = info
      - equal:
          - namespace
        source_matchers:
          - alertname = InfoInhibitor
        target_matchers:
          - severity = info
      - target_matchers:
          - alertname = InfoInhibitor

    receivers:
      - name: "null"
      - name: slack
        slack_configs:
          - channel: '#monitoring-cdsl-alert'
            send_resolved: true
            text: |-
              {{ range $index, $alert := .Alerts }}
                ---------------------------
                *アラート:* {{ $alert.Labels.alertname }} 
                *概要:* {{ if $alert.Annotations.summary }}{{ $alert.Annotations.summary }}{{ else }}概要なし{{ end }}
                *ランブック:* {{ if $alert.Annotations.runbook_url }}{{ $alert.Annotations.runbook_url }}{{ else }}https://github.com/prometheus-operator/runbooks/{{ end }}
                *重大度:* {{ $alert.Labels.severity }}
                *詳細情報:*
                  • *alertname:* {{ $alert.Labels.alertname }}
                  • *instance:* {{ if $alert.Labels.instance }}{{ $alert.Labels.instance }}{{ else }}N/A{{ end }}
                  • *job:* {{ if $alert.Labels.job }}{{ $alert.Labels.job }}{{ else }}N/A{{ end }}
                  • *description:* {{ if $alert.Annotations.description }}{{ $alert.Annotations.description }}{{ else }}説明なし{{ end }}
              {{ end }}
              ---------------------------
            title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] 監視イベント通知'

    route:
      group_interval: 5m
      group_wait: 5m
      group_by:
        - instance
        - alertname
      repeat_interval: 12h
      receiver: "slack"
      routes:
        - match:
            alertname: DeadMansSwitch
          receiver: "null"
        - receiver: slack
          continue: true
