apiVersion: v1
kind: ConfigMap
metadata:
  name: lidar-server-rule
  namespace: monitoring
data:
  lidar-monitoring-rules.yml: |-
    ### Trafic
    groups:
    - name: Internal-Lidar-System-Check
      rules:
      ### ICMP
      - alert: Internal from Lidar to Iris ICMP-Check
        annotations:
          alert_title: "Internal {{ $labels.instance }} ICMP Check"
          description: "Instance {{$labels.instance}} not connect"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "From Lidar to Iris ICMP not connect"
        expr: |-
          probe_success{job="Internal-ICMP-lidar"} == 0
        for: 1m
        labels:
          severity: critical

      - alert: Internal output Lidar data check port 8001
        annotations:
          alert_title: "Internal {{ $labels.instance }} data check port 8001"
          description: "Instance {{$labels.instance}} not output"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "Lidar data not output port 8001"
        expr: |-
          lidar_data_received{port="8001"} == 0
        for: 1m
        labels:
          severity: critical

      - alert: Internal output Lidar data check port 8002
        annotations:
          alert_title: "Internal {{ $labels.instance }} data check port 8002"          
          description: "Instance {{$labels.instance}} not output"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "Lidar data not output port 8002"
        expr: |- 
          lidar_data_received{port="8002"} == 0
        for: 1m                                                                     
        labels:
          severity: critical
