# jasmine用deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-exporter-jasmine
spec:
  selector:
    matchLabels:
      app: vmware-exporter
      release: jasmine
  template:
    metadata:
      labels:
        app: vmware-exporter
        release: jasmine
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9272"
        prometheus.io/scrape: "true"
    spec:
      nodeSelector:
        node: monitoring-worker1
      containers:
      - name: vmware-exporter
        image: "pryorda/vmware_exporter:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 9272
          name: http
        envFrom:
        - configMapRef:
            name: vmware-exporter-config-jasmine
        - secretRef:
            name: vmware-exporter-password-jasmine
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m"
---
#rose用deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-exporter-rose
spec:
  selector:
    matchLabels:
      app: vmware-exporter
      release: rose
  template:
    metadata:
      labels:
        app: vmware-exporter
        release: rose
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9272"
        prometheus.io/scrape: "true"
    spec:
      nodeSelector:
        node: monitoring-worker1
      containers:
      - name: vmware-exporter
        image: "pryorda/vmware_exporter:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 9272
          name: http
        envFrom:
        - configMapRef:
            name: vmware-exporter-config-rose
        - secretRef:
            name: vmware-exporter-password-rose
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m"
---
#lotus用deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-exporter-lotus
spec:
  selector:
    matchLabels:
      app: vmware-exporter
      release: lotus
  template:
    metadata:
      labels:
        app: vmware-exporter
        release: lotus
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9272"
        prometheus.io/scrape: "true"
    spec:
      nodeSelector:
        node: monitoring-worker1
      containers:
      - name: vmware-exporter
        image: "pryorda/vmware_exporter:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 9272
          name: http
        envFrom:
        - configMapRef:
            name: vmware-exporter-config-lotus
        - secretRef:
            name: vmware-exporter-password-lotus
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m"
---
#violet用deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-exporter-violet
spec:
  selector:
    matchLabels:
      app: vmware-exporter
      release: violet
  template:
    metadata:
      labels:
        app: vmware-exporter
        release: violet
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9272"
        prometheus.io/scrape: "true"
    spec:
      nodeSelector:
        node: monitoring-worker1
      containers:
      - name: vmware-exporter
        image: "pryorda/vmware_exporter:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 9272
          name: http
        envFrom:
        - configMapRef:
            name: vmware-exporter-config-violet
        - secretRef:
            name: vmware-exporter-password-violet
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m"
---
#mint用deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-exporter-mint
spec:
  selector:
    matchLabels:
      app: vmware-exporter
      release: mint
  template:
    metadata:
      labels:
        app: vmware-exporter
        release: mint
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9272"
        prometheus.io/scrape: "true"
    spec:
      nodeSelector:
        node: monitoring-worker1
      containers:
      - name: vmware-exporter
        image: "pryorda/vmware_exporter:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 9272
          name: http
        envFrom:
        - configMapRef:
            name: vmware-exporter-config-mint
        - secretRef:
            name: vmware-exporter-password-mint
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m"
---
#plum用deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-exporter-plum
spec:
  selector:
    matchLabels:
      app: vmware-exporter
      release: plum
  template:
    metadata:
      labels:
        app: vmware-exporter
        release: plum
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9272"
        prometheus.io/scrape: "true"
    spec:
      nodeSelector:
        node: monitoring-worker1
      containers:
      - name: vmware-exporter
        image: "pryorda/vmware_exporter:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 9272
          name: http
        envFrom:
        - configMapRef:
            name: vmware-exporter-config-plum
        - secretRef:
            name: vmware-exporter-password-plum
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m"
---
#Iris用deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-exporter-iris
spec:
  selector:
    matchLabels:
      app: vmware-exporter
      release: iris
  template:
    metadata:
      labels:
        app: vmware-exporter
        release: iris
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9272"
        prometheus.io/scrape: "true"
    spec:
      nodeSelector:
        node: monitoring-worker1
      containers:
      - name: vmware-exporter
        image: "pryorda/vmware_exporter:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 9272
          name: http
        envFrom:
        - configMapRef:
            name: vmware-exporter-config-iris
        - secretRef:
            name: vmware-exporter-password-iris
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m"
---
#lily用deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-exporter-lily
spec:
  selector:
    matchLabels:
      app: vmware-exporter
      release: lily
  template:
    metadata:
      labels:
        app: vmware-exporter
        release: lily
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9272"
        prometheus.io/scrape: "true"
    spec:
      nodeSelector:
        node: monitoring-worker1
      containers:
      - name: vmware-exporter
        image: "pryorda/vmware_exporter:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 9272
          name: http
        envFrom:
        - configMapRef:
            name: vmware-exporter-config-lily
        - secretRef:
            name: vmware-exporter-password-lily
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m"
---
#makaron用deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-exporter-makaron
spec:
  selector:
    matchLabels:
      app: vmware-exporter
      release: makaron
  template:
    metadata:
      labels:
        app: vmware-exporter
        release: makaron
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9272"
        prometheus.io/scrape: "true"
    spec:
      nodeSelector:
        node: monitoring-worker1
      containers:
      - name: vmware-exporter
        image: "pryorda/vmware_exporter:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 9272
          name: http
        envFrom:
        - configMapRef:
            name: vmware-exporter-config-makaron
        - secretRef:
            name: vmware-exporter-password-makaron
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m"
---
#canele用deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-exporter-canele
spec:
  selector:
    matchLabels:
      app: vmware-exporter
      release: canele
  template:
    metadata:
      labels:
        app: vmware-exporter
        release: canele
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9272"
        prometheus.io/scrape: "true"
    spec:
      nodeSelector:
        node: monitoring-worker1
      containers:
      - name: vmware-exporter
        image: "pryorda/vmware_exporter:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 9272
          name: http
        envFrom:
        - configMapRef:
            name: vmware-exporter-config-canele
        - secretRef:
            name: vmware-exporter-password-canele
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m"
---
#jasmine用service
apiVersion: v1
kind: Service
metadata:
  name: vmware-exporter-service-jasmine
spec:
  selector:
    app: vmware-exporter
    release: jasmine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9272
      nodePort: 32700
  type: NodePort
---
#rose用service
apiVersion: v1
kind: Service
metadata:
  name: vmware-exporter-service-rose
spec:
  selector:
    app: vmware-exporter
    release: rose
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9272
      nodePort: 32701
  type: NodePort
---
#lotus用service
apiVersion: v1
kind: Service
metadata:
  name: vmware-exporter-service-lotus
spec:
  selector:
    app: vmware-exporter
    release: lotus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9272
      nodePort: 32702
  type: NodePort
---
#violet用service
apiVersion: v1
kind: Service
metadata:
  name: vmware-exporter-service-violet
spec:
  selector:
    app: vmware-exporter
    release: violet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9272
      nodePort: 32703
  type: NodePort
---
#mint用service
apiVersion: v1
kind: Service
metadata:
  name: vmware-exporter-service-mint
spec:
  selector:
    app: vmware-exporter
    release: mint
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9272
      nodePort: 32704
  type: NodePort
---
#plum用service
apiVersion: v1
kind: Service
metadata:
  name: vmware-exporter-service-plum
spec:
  selector:
    app: vmware-exporter
    release: plum
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9272
      nodePort: 32705
  type: NodePort
---
#lily用service
apiVersion: v1
kind: Service
metadata:
  name: vmware-exporter-service-lily
spec:
  selector:
    app: vmware-exporter
    release: lily
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9272
      nodePort: 32706
  type: NodePort
---
  #Iris用service
apiVersion: v1
kind: Service
metadata:
  name: vmware-exporter-service-iris
spec:
  selector:
    app: vmware-exporter
    release: iris
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9272
      nodePort: 32707
  type: NodePort
---
#makaron用service
apiVersion: v1
kind: Service
metadata:
  name: vmware-exporter-service-makaron
spec:
  selector:
    app: vmware-exporter
    release: makaron
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9272
      nodePort: 32708
  type: NodePort
---
#canele用service
apiVersion: v1
kind: Service
metadata:
  name: vmware-exporter-service-canele
spec:
  selector:
    app: vmware-exporter
    release: canele
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9272
      nodePort: 32709
  type: NodePort
