apiVersion: v1
kind: ConfigMap
metadata:
  name: esxi-rule
  namespace: monitoring
data:
  esxi-monitoring-rules.yml: |-
    groups:
    - name: Internal-ESXi-Check
      rules:
        #- alert: Internal ESXi ICMP Check
        #annotations:
        #alert_title: "Internal {{ $labels.instance }} ICMP Check"
        #description: "Instance {{$labels.instance}} not connect"
        #runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
        #summary: "ESXi ICMP not connect"
        #expr: |-
        #probe_success{job="Internal-ICMP-ESXi-Host"} == 0 and switchbot_power_status{job="switchbot"} == 1
        #for: 30m
        #labels:
        #severity: critical

      - alert: Test plum ICMP Check
        annotations:
          alert_title: "{{ $labels.instance }} ICMP not connect but Switchbot {{ $labels.device_name }} up"
          description: "Instance {{$labels.instance}} not connect"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "ESXi ICMP not connect"
        expr: |-
          switchbot_power_status{device_name="plum"} == 1 and on() probe_success{instance="plum"} == 0
        for: 30m
        labels:
          severity: critical

      - alert: Test jasmine ICMP Check
        annotations:
          alert_title: "{{ $labels.instance }} ICMP not connect but Switchbot {{ $labels.device_name }} up"
          description: "Instance {{$labels.instance}} not connect"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "ESXi ICMP not connect"
        expr: |-
          switchbot_power_status{device_name="jasmine"} == 1 and on() probe_success{instance="jasmine"} == 0
        for: 30m
        labels:
          severity: critical

      - alert: Test rose ICMP Check
        annotations:
          alert_title: "{{ $labels.instance }} ICMP not connect but Switchbot {{ $labels.device_name }} up"
          description: "Instance {{$labels.instance}} not connect"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "ESXi ICMP not connect"
        expr: |-
          switchbot_power_status{device_name="rose"} == 1 and on() probe_success{instance="rose"} == 0
        for: 30m
        labels:
          severity: critical

      - alert: Test lotus ICMP Check
        annotations:
          alert_title: "{{ $labels.instance }} ICMP not connect but Switchbot {{ $labels.device_name }} up"
          description: "Instance {{$labels.instance}} not connect"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "ESXi ICMP not connect"
        expr: |-
          switchbot_power_status{device_name="lotus"} == 1 and on() probe_success{instance="lotus"} == 0
        for: 30m
        labels:
          severity: critical

      - alert: Test violet ICMP Check
        annotations:
          alert_title: "{{ $labels.instance }} ICMP not connect but Switchbot {{ $labels.device_name }} up"
          description: "Instance {{$labels.instance}} not connect"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "ESXi ICMP not connect"
        expr: |-
          switchbot_power_status{device_name="violet"} == 1 and on() probe_success{instance="violet"} == 0
        for: 30m
        labels:
          severity: critical

      - alert: Test mint ICMP Check
        annotations:
          alert_title: "{{ $labels.instance }} ICMP not connect but Switchbot {{ $labels.device_name }} up"
          description: "Instance {{$labels.instance}} not connect"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: "ESXi ICMP not connect"
        expr: |-
          switchbot_power_status{device_name="mint"} == 1 and on() probe_success{instance="mint"} == 0
        for: 30m
        labels:
          severity: critical

      - alert: Internal DataStore Connection Unavailable
        annotations:
          alert_title: "DS {{ $labels.ds_name }} Connection Unavailable"
          description: "`Host: {{$labels.instance}}` Ds_name: `{{$labels.ds_name}}` Not Connection"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary:  "DataStore Not Connection"
        expr: |-
          vmware_datastore_accessible{job="Internal-ESXI_exporter", ds_name!="StoreNAS-Public"} == 0
        for: 3m
        labels:
          severity: critical

      - alert: Internal HostMemoryUsageHigh-Usage90%
        annotations:
          alert_title: "{{$labels.host_name}} MemoryUsageHigh-Usage90%"
          description: "Host Name: `{{$labels.host_name}}` Memory Usage 95%"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary:  "Memory Usage High"
        expr: |-
          vmware_host_memory_usage{job="Internal-ESXI_exporter"} / vmware_host_memory_max{job="Internal-ESXI_exporter"} * 100 >= 90
        for: 3m
        labels:
          severity: critical

      - alert: Internal DataStoreDiskUsageHigh-Usage 90%
        annotations:
          alert_title: "DataStore {{$labels.ds_name}} DiskUsageHigh-Usage 90%"
          description: "Host Name: `{{$labels.instance}}`, Ds_name: `{{$labels.ds_name}}` Disk Usage High"
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary:  "Disk Usage High"
        expr: ((vmware_datastore_capacity_size{ds_name=~"StoreNAS.*|store-m2|datastore1",job="Internal-ESXI_exporter"} - vmware_datastore_freespace_size{ds_name=~"StoreNAS.*|store-m2|datastore1",job="Internal-ESXI_exporter"}) / vmware_datastore_capacity_size{ds_name=~"StoreNAS.*|store-m2|datastore1",job="Internal-ESXI_exporter"} * 100) >= 90 unless vmware_datastore_capacity_size{ds_name=~".*(Public|Backup).*",job="Internal-ESXI_exporter"}
        for: 3m
        labels:
          severity: critical

      # - alert: ESXi-Monitoring-ICMP-Responce-time-1.0
      #   annotations:
      #     description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary: "ICMP response time delay"
      #   expr: |-
      #     probe_duration_seconds{job="ICMP-ESXi-Host"} >= 1.0
      #   for: 3m
      #   labels:
      #     severity: warning

      # - alert: ESXi-Monitoring-ICMP-Responce-time-3.0
      #   annotations:
      #     description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary: "ICMP response time delay"
      #   expr: |-
      #     probe_duration_seconds{job="ICMP-ESXi-Host"} >= 3.0
      #   for: 3m
      #   labels:
      #     severity: warning

      
      # ### HTTP
      # - alert: ESXi-HTTP-Check
      #   annotations:
      #     description: "Instance {{$labels.instance}} not connect"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary: "ESXi HTTP not connect"
      #   expr: |-
      #     probe_success{job="HTTP-ESXi"} == 0
      #   for: 3m
      #   labels:
      #     severity: critical

      # - alert: ESXi-Monitoring-HTTP-Responce-time-1.0
      #   annotations:
      #     description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary: "HTTP response time delay"
      #   expr: |-
      #     probe_duration_seconds{job="HTTP-ESXi"} >= 1.0
      #   for: 3m
      #   labels:
      #     severity: warning

      # - alert: ESXi-Monitoring-HTTP-Responce-time-3.0
      #   annotations:
      #     description: "job {{$labels.job}} Instance {{$labels.instance}} response-time-delay"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary: "HTTP response time delay"
      #   expr: |-
      #     probe_duration_seconds{job="HTTP-ESXi"} >= 3.0
      #   for: 3m
      #   labels:
      #     severity: warning

      # - alert: ESXi-Monitoring-HTTP-StatusCode-Err
      #   annotations:
      #     description: "job {{$labels.job}} Instance {{$labels.instance}} StatusCode Err"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary: "StatusCode Err"
      #   expr: |-
      #     probe_http_status_code{job="HTTP-ESXi"} >= 400
      #   for: 3m
      #   labels:
      #     severity: warning

      ### Connection Rules
      # - alert: HostConnectionUnavailable
      #   annotations:
      #     description: "`{{$labels.host_name}}` Host Connection"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary:  "`{{$labels.host_name}}` Host Connection"
      #   expr: |-
      #     vmware_host_connection_state{job="ESXI_exporter"} == 0
      #   for: 3m
      #   labels:
      #     severity: critical

      # - alert: DataStoreConnectionUnavailable
      #   annotations:
      #     description: "`Host: {{$labels.instance}}` Ds_name: `{{$labels.ds_name}}` Not Connection"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary:  "DataStore Not Connection"
      #   expr: |-
      #     vmware_datastore_accessible{job="ESXI_exporter", ds_name!="StoreNAS-Public"} == 0
      #   for: 3m
      #   labels:
      #     severity: critical

      ### CPU Rules
      # - alert: HostCPUUsageHighWarning
      #   annotations:
      #     description: "Host Name: `{{$labels.host_name}}` CPU Usage High"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary:  "CPU Usage High"
      #   expr: |-
      #     vmware_host_cpu_usage{job="ESXI_exporter"}/vmware_host_cpu_max{job="ESXI_exporter"} * 100 >= 80
      #   for: 3m
      #   labels:
      #     severity: warning
      
      # - alert: HostCPUUsageHighCritical
      #   annotations:
      #     description: "Host Name: `{{$labels.host_name}}` CPU Usage High"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary:  "CPU Usage High"
      #   expr: |-
      #     vmware_host_cpu_usage{job="ESXI_exporter"}/vmware_host_cpu_max{job="ESXI_exporter"} * 100 >= 90
      #   for: 3m
      #   labels:
      #     severity: critical

      ### Memory Rules
      # - alert: HostMemoryUsageHighWarning
      #   annotations:
      #     description: "Host Name: `{{$labels.host_name}}` Memory Usage High"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary:  "Memory Usage High"
      #   expr: |-
      #     vmware_host_memory_usage{job="ESXI_exporter"}/vmware_host_memory_max{job="ESXI_exporter"} * 100 >= 80
      #   for: 3m
      #   labels:
      #     severity: warning

      

      ### Disk Rules
      # - alert: DataStoreDiskUsageHigh
      #   annotations:
      #     description: "Host Name: `{{$labels.instance}}`, Ds_name: `{{$labels.ds_name}}` Disk Usage High"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary:  "Disk Usage High"
      #   expr: ((vmware_datastore_capacity_size{ds_name=~"StoreNAS.*|store-m2|datastore1",job="ESXI_exporter"} - vmware_datastore_freespace_size{ds_name=~"StoreNAS.*|store-m2|datastore1",job="ESXI_exporter"}) / vmware_datastore_capacity_size{ds_name=~"StoreNAS.*|store-m2|datastore1",job="ESXI_exporter"} * 100) >= 80 unless vmware_datastore_capacity_size{ds_name=~".*(Public|Backup).*",job="ESXI_exporter"} 
      #   for: 3m
      #   labels:
      #     severity: warning


      ### Network Rules
      # - alert: NetworkPacketLossReceive
      #   annotations:
      #     description: "Host Name: `{{$labels.host_name}}` Packet Loss Error"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary:  "Packet Loss Error"
      #   expr: |-
      #     vmware_host_net_droppedRx_summation{job="ESXI_exporter"} / vmware_host_net_bytesRx_average{job="ESXI_exporter"} > 0
      #   for: 3m
      #   labels:
      #     severity: warning

      # - alert: NetworkPacketLossTransmit
      #   annotations:
      #     description: "Host Name: `{{$labels.host_name}}` Packet Loss Error"
      #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
      #     summary:  "Packet Loss Error"
      #   expr: |-
      #     vmware_host_net_droppedTx_summation{job="ESXI_exporter"} / vmware_host_net_bytesTx_average{job="ESXI_exporter"} > 0
      #   for: 3m
      #   labels:
      #     severity: warning


    
